# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import particle_data_pb2 as particle__data__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in particle_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ParticleDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateParticles = channel.unary_unary(
                '/ParticleRender.ParticleDataService/UpdateParticles',
                request_serializer=particle__data__pb2.ParticleDataRequest.SerializeToString,
                response_deserializer=particle__data__pb2.ParticleDataResponse.FromString,
                _registered_method=True)
        self.UpdateVoxelGrid = channel.unary_unary(
                '/ParticleRender.ParticleDataService/UpdateVoxelGrid',
                request_serializer=particle__data__pb2.VoxelGridDataRequest.SerializeToString,
                response_deserializer=particle__data__pb2.VoxelGridDataResponse.FromString,
                _registered_method=True)
        self.UpdateParticleFrame = channel.unary_unary(
                '/ParticleRender.ParticleDataService/UpdateParticleFrame',
                request_serializer=particle__data__pb2.ParticleFrameRequest.SerializeToString,
                response_deserializer=particle__data__pb2.ParticleFrameResponse.FromString,
                _registered_method=True)
        self.EndSimulation = channel.unary_unary(
                '/ParticleRender.ParticleDataService/EndSimulation',
                request_serializer=particle__data__pb2.EndSimulationRequest.SerializeToString,
                response_deserializer=particle__data__pb2.EndSimulationResponse.FromString,
                _registered_method=True)


class ParticleDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateParticles(self, request, context):
        """Legacy particle-based interface (deprecated, kept for compatibility)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVoxelGrid(self, request, context):
        """Voxel grid-based interface (方案二: 密度场传输)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateParticleFrame(self, request, context):
        """New: Quantized particle frame interface (方案三: 粒子传输 + GPU 密度场重建)
        Benefits: 50x smaller data transfer, GPU-side density reconstruction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndSimulation(self, request, context):
        """Simulation lifecycle: notify the renderer that the simulation has ended
        The renderer will reset the fluid to its initial (invisible) state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParticleDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateParticles': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateParticles,
                    request_deserializer=particle__data__pb2.ParticleDataRequest.FromString,
                    response_serializer=particle__data__pb2.ParticleDataResponse.SerializeToString,
            ),
            'UpdateVoxelGrid': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVoxelGrid,
                    request_deserializer=particle__data__pb2.VoxelGridDataRequest.FromString,
                    response_serializer=particle__data__pb2.VoxelGridDataResponse.SerializeToString,
            ),
            'UpdateParticleFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateParticleFrame,
                    request_deserializer=particle__data__pb2.ParticleFrameRequest.FromString,
                    response_serializer=particle__data__pb2.ParticleFrameResponse.SerializeToString,
            ),
            'EndSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.EndSimulation,
                    request_deserializer=particle__data__pb2.EndSimulationRequest.FromString,
                    response_serializer=particle__data__pb2.EndSimulationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ParticleRender.ParticleDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ParticleRender.ParticleDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ParticleDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateParticles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ParticleRender.ParticleDataService/UpdateParticles',
            particle__data__pb2.ParticleDataRequest.SerializeToString,
            particle__data__pb2.ParticleDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateVoxelGrid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ParticleRender.ParticleDataService/UpdateVoxelGrid',
            particle__data__pb2.VoxelGridDataRequest.SerializeToString,
            particle__data__pb2.VoxelGridDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateParticleFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ParticleRender.ParticleDataService/UpdateParticleFrame',
            particle__data__pb2.ParticleFrameRequest.SerializeToString,
            particle__data__pb2.ParticleFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ParticleRender.ParticleDataService/EndSimulation',
            particle__data__pb2.EndSimulationRequest.SerializeToString,
            particle__data__pb2.EndSimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
