framework: "rllib"
orcagym_addresses: ["localhost:50051"]
ray_cluster_address: "ray://localhost:6379"
agent_name: "Lite3"
task: "flat_terrain"
env_name: "LeggedGym"

agents_per_env: 32
use_robot_locator: false

training:
  max_episode_steps: 1000
  num_env_runners: 0
  num_envs_per_env_runner: 32
  num_cpus_per_env_runner: 1
  num_gpus_per_env_runner: 0.01
  num_learners: 1
  num_cpus_per_learner: 8
  num_gpus_per_learner: 0.6
  async_env_runner: True
  iter: 2000
  render_mode: none
  frame_skip: 5
  action_skip: 4
  time_step: 0.001
  terrain_asset_paths:
    flat_terrain: ["assets/e071469a36d3c8aa/default_project/prefabs/terrain_ellipsoid_low_usda"]
    rough_terrain: ["assets/e071469a36d3c8aa/default_project/prefabs/terrain_stair_low_usda"]
  curriculum_list:
    flat_terrain:
      - name: "flat_terrain"
        milestone: 2000
    rough_terrain:
      - name: "rough_terrain"
        milestone: 2000

testing:
  agent_name: "Lite3_000"
  max_episode_steps: 1000
  render_mode: human
  num_env_runners: 1
  num_envs_per_env_runner: 1
  num_cpus_per_env_runner: 1
  num_gpus_per_env_runner: 0
  num_learners: 1
  num_cpus_per_learner: 4
  num_gpus_per_learner: 0.5
  async_env_runner: True
  iter: 2000
  frame_skip: 5
  action_skip: 4
  time_step: 0.001
  terrain_asset_paths:
    flat_terrain: ["assets/e071469a36d3c8aa/default_project/prefabs/terrain_ellipsoid_low_usda"]
    rough_terrain: ["assets/e071469a36d3c8aa/default_project/prefabs/terrain_stair_low_usda"]
  curriculum_list:
    flat_terrain:
      - name: "flat_terrain"
        milestone: 2000
    rough_terrain:
      - name: "rough_terrain"
        milestone: 2000

play:
  agent_name: "Lite3_000"
  max_episode_steps: 1000
  render_mode: human
  num_env_runners: 1
  num_envs_per_env_runner: 1
  num_cpus_per_env_runner: 1
  num_gpus_per_env_runner: 0
  num_learners: 1
  num_cpus_per_learner: 4
  num_gpus_per_learner: 0.5
  async_env_runner: True
  iter: 2000
  frame_skip: 5
  action_skip: 4
  time_step: 0.001
