framework: "sb3"
orcagym_addresses: ["localhost:50051"]
agent_name: "Lite3"
training_episode: 100
task: "flat_terrain"

training:
  subenv_num: 64
  agent_num: 16
  render_mode: "none"
  terrain_asset_paths:
    flat_terrain: []
  curriculum_list:
    flat_terrain:
      - name: "flat_terrain"
        milestone: 1500

testing:
  subenv_num: 1
  agent_num: 8
  render_mode: "human"
  terrain_asset_paths:
    flat_terrain: []
  curriculum_list:
    flat_terrain:
      - name: "flat_terrain"
        milestone: 2000

play:
  subenv_num: 1
  agent_num: 1
  render_mode: "human"
  terrain_asset_paths:
    flat_terrain: []
  curriculum_list:
    flat_terrain:
      - name: "flat_terrain"
        milestone: 2000