framework: "sb3"
orcagym_addresses: ["localhost:50051"]
model_name: "panda"
task: "pick_and_place"
reward_type: "dense"
model_type: "sac"
training_episode: 200
start_her_episode: 1.0

training:
  subenv_num: 1
  render_mode: "human"

testing:
  subenv_num: 1
  render_mode: "human"
