# Ant Local Training/Testing Configuration
# Single machine, single/multi-environment parallel training

train_ant_local:
  orcagym_addr: "localhost:50051"
  env_name: "Ant_OrcaGymEnv"
  agent_name: "ant_usda"
  max_episode_steps: 1000
  num_env_runners: 4
  num_envs_per_env_runner: 32
  agents_per_env: 1
  async_env_runner: False
  frame_skip: 5
  action_skip: 1
  time_step: 0.01
  run_mode: training
  iter: 50
  render_mode: none

test_ant_local:
  orcagym_addr: "localhost:50051"
  env_name: "Ant_OrcaGymEnv"
  agent_name: "ant_usda"
  max_episode_steps: 1000
  agents_per_env: 1
  frame_skip: 5
  action_skip: 1
  time_step: 0.01
  run_mode: testing
  render_mode: human
